Repository dfinity/motoko, pull requests merged in 2021-08, with the labels that each got.

#2701 RTS: compile blob_iter module only when compiling for ic, remove feature=ic guards
  rts/motoko-rts/src/blob_iter.rs
  rts/motoko-rts/src/lib.rs
Labels: automerge-squash

#2707 RTS: Introduce heap objects for unused space
  rts/motoko-rts/src/debug.rs
  rts/motoko-rts/src/principal_id.rs
  rts/motoko-rts/src/types.rs
  rts/motoko-rts/src/visitor.rs
  src/codegen/compile.ml
Labels: automerge-squash

#2670 Nix gardening
  nix/default.nix
  nix/ocaml-obelisk.nix
  nix/ocaml-vlq.nix
  nix/xargo.nix
Labels: automerge-squash

#2710 Use compile_eq_const
  src/codegen/compile.ml
Labels: automerge-squash

#2711 src/Makefile: Create/delete source_id/generated.ml
  src/Makefile
Labels: automerge-squash

#2712 nix-shell: Do not include nix-built candid-tests
  default.nix
Labels: automerge-squash

#2719 Use deterministic hashers in RTS test suite
  default.nix
  rts/motoko-rts-tests/Cargo.lock
  rts/motoko-rts-tests/Cargo.toml
  rts/motoko-rts-tests/src/gc.rs
  rts/motoko-rts-tests/src/gc/heap.rs
  rts/motoko-rts-tests/src/main.rs
Labels: automerge-squash

#2720 Update IDE config for rts
  rts/motoko-rts/.vim/coc-settings.json
Labels: automerge-squash

#2721 Fix handling of self references in mark-compact GC, imrpove tests
  rts/motoko-rts-tests/src/gc.rs
  rts/motoko-rts-tests/src/gc/heap.rs
  rts/motoko-rts/src/gc/mark_compact.rs
Labels: automerge-squash

#2643 ci-pr.nix: Fix wasm-hash-for
  ci-pr.nix
Labels: automerge-squash

#2708 Optimise field access by computing the minimal positional index
  src/codegen/compile.ml
  test/run/idx.mo
Labels: automerge-squash, performance

#2725 Releasing 0.6.7
  Changelog.md
Labels: automerge-squash

#2726 nix: create dedicated ic-ref-run derivation
  default.nix
Labels: automerge-squash

#2722 Improve on #2708 by applying strength reduction and abolishing termination checks
  src/codegen/compile.ml
  src/codegen/instrList.ml
Labels: automerge-squash

#2727 Add tests to check for compilation of bottom (as object)
  test/run/idx.mo
Labels: automerge-squash

#2737 Increase the buffer for storing the float string
  rts/motoko-rts/src/float.rs
Labels: Bug, automerge-squash

#2742 RTS: Shift scalar values by one instead of two
  rts/motoko-rts/src/blob_iter.rs
  rts/motoko-rts/src/continuation_table.rs
Labels: automerge-squash

#2733 Implement `Int` ⇔ `Float` conversion as primitives
  rts/Makefile
  rts/motoko-rts/src/bigint.rs
  rts/motoko-rts/src/types.rs
  src/codegen/compile.ml
  src/mo_values/numerics.ml
  src/mo_values/numerics.mli
  src/mo_values/prim.ml
  src/prelude/prim.mo
  test/run/float-ops.mo
  test/run/ok/float-ops.run-ir.ok
  test/run/ok/float-ops.run-low.ok
  test/run/ok/float-ops.run.ok
  test/run/ok/float-ops.wasm-run.ok
Labels: automerge-squash

#2745 hydra: Don't comment on perf changes
  ci-pr.nix
Labels: automerge-squash

#2746 CI: Include revisions in perf change comment
  perf-delta.nix
Labels: automerge-squash

#2738 Refactor SkewedPtr type
  rts/motoko-rts-tests/src/bigint.rs
  rts/motoko-rts-tests/src/continuation_table.rs
  rts/motoko-rts-tests/src/gc.rs
  rts/motoko-rts-tests/src/gc/heap.rs
  rts/motoko-rts-tests/src/memory.rs
  rts/motoko-rts-tests/src/text.rs
  rts/motoko-rts/src/bigint.rs
  rts/motoko-rts/src/blob_iter.rs
  rts/motoko-rts/src/continuation_table.rs
  rts/motoko-rts/src/debug.rs
  rts/motoko-rts/src/float.rs
  rts/motoko-rts/src/gc/copying.rs
  rts/motoko-rts/src/gc/mark_compact.rs
  rts/motoko-rts/src/gc/mark_compact/bitmap.rs
  rts/motoko-rts/src/gc/mark_compact/mark_stack.rs
  rts/motoko-rts/src/lib.rs
  rts/motoko-rts/src/memory.rs
  rts/motoko-rts/src/memory/ic.rs
  rts/motoko-rts/src/principal_id.rs
  rts/motoko-rts/src/text.rs
  rts/motoko-rts/src/text_iter.rs
  rts/motoko-rts/src/types.rs
  rts/motoko-rts/src/visitor.rs
Labels: automerge-squash

#2744 CI.md: Mention branch protection
  CI.md
Labels: automerge-squash
