Repository dfinity/motoko, pull requests merged in 2022-06, with the labels that each got.

#3279 chore: preparations for #3231
  rts/motoko-rts/src/gc/mark_compact.rs
  rts/motoko-rts/src/gc/mark_compact/mark_stack.rs
  rts/motoko-rts/src/types.rs
Labels: automerge-squash

#3283 feat: refactor `stableVarQuery` as prim returning an obviously pure (and more efficient) query
  src/codegen/compile.ml
  src/lowering/desugar.ml
  src/mo_types/type.ml
  src/mo_types/type.mli
  src/prelude/internals.mo
  src/prelude/prim.mo
  test/fail/ok/illegal-await.tc.ok
  test/run-drun/ok/query-footprint.ic-ref-run.ok
  test/run-drun/query-footprint-overflow.mo
  test/run-drun/query-footprint.mo
Labels: automerge-squash

#3231 feat: introduce array-slice processing for compacting GC
  rts/motoko-rts/src/gc/copying.rs
  rts/motoko-rts/src/gc/mark_compact.rs
  rts/motoko-rts/src/types.rs
  rts/motoko-rts/src/visitor.rs
Labels: automerge-squash

#3285 feat: expose `ExperimentalStableMemory.stableVarQuery`
  Changelog.md
  doc/modules/language-guide/pages/stablememory.adoc
  nix/sources.json
Labels: automerge-squash

#3263 Improve support for navigating to definitions in external modules
  src/languageServer/definition.ml
  test/lsp-int/Main.hs
Labels: automerge-squash, cla:agreed

#3286 Update doc for interpreter support for markdown
  doc/README.md
Labels: automerge-squash

#3282 Add basic language server support for explicit symbol imports
  src/languageServer/completion.ml
  src/languageServer/definition.ml
  src/languageServer/hover.ml
  src/languageServer/source_file.ml
  src/languageServer/source_file_tests.ml
  test/lsp-int-test-project/definitions.mo
  test/lsp-int/Main.hs
Labels: automerge-squash, cla:agreed

#3288 feat: expose `ic0.performance_counter`
  nix/drun.nix
  nix/sources.json
  src/codegen/compile.ml
  src/prelude/prim.mo
  test/run-drun/ok/perf.drun-run.ok
  test/run-drun/ok/perf.ic-ref-run.ok
  test/run-drun/perf.mo
Labels: automerge-squash

#3296 feat: expose `ExperimentalInternetComputer.countInstructions(comp)`
  Changelog.md
  nix/sources.json
Labels: automerge-squash

#3301 Abolish `UnboxedBool` stack representation
  src/codegen/compile.ml
  test/run/array.mo
  test/run/ok/array.tc.ok
Labels: automerge-squash

#3305 Releasing 0.6.29
  Changelog.md
Labels: automerge-squash

#3309 Fix stray logging in `mo-doc` and other cleanups
  src/docs/extract.ml
  src/exes/mo_doc.ml
  src/ic/url_test.ml
  src/idllib/arrange_idl.ml
  src/ir_def/arrange_ir.ml
  src/ir_def/rename.ml
  src/ir_passes/tailcall.ml
  src/lowering/desugar.ml
  src/mo_def/arrange.ml
  src/mo_types/arrange_type.ml
  src/mo_types/expansive.ml
  src/mo_types/productive.ml
  src/mo_types/type.ml
Labels: automerge-squash

#3319 bugfix: improve pretty printing of function types to reflect arity differences (issue #3318)
  src/mo_types/type.ml
  test/fail/issue-3318.mo
  test/fail/ok/issue-3318.tc.ok
  test/fail/ok/issue-3318.tc.ret.ok
Labels: automerge-squash

#3112 Shift primitives for `Nat`
  rts/motoko-rts/src/bigint.rs
  src/codegen/compile.ml
  src/mo_values/prim.ml
  src/prelude/prim.mo
  test/run/nat-shift.mo
  test/run/ok/nat-shift.tc.ok
Labels: automerge-squash, opportunity

#3337 Bump some GH actions
  .github/workflows/test.yml
Labels: automerge-squash
