Repository dfinity/motoko, pull requests merged in 2022-11, with the labels that each got.

#3534 chore: rebuild doc; update changelog in preparation for release 0.7.3
  Changelog.md
  doc/docusaurus/static/load_moc.ts
  doc/md/base/Buffer.md
Labels: automerge-squash

#3536 Releasing 0.7.3
  Changelog.md
Labels: automerge-squash

#3547 chore: remove use of `set-output` from CI
  .github/workflows/release.yml
Labels: automerge-squash

#3553 chore: quote the GitHub output file
  .github/workflows/release.yml
Labels: automerge-squash

#3554 Minor cleanup: Partially revert because of performance degrade
  rts/motoko-rts/src/memory/ic.rs
  test/bench/ok/heap-32.drun-run.ok
  test/bench/ok/palindrome.drun-run.ok
Labels: automerge-squash

#3551 Backend: Correctly join Const and UnboxedTuple reps
  src/codegen/compile.ml
  test/run/join-const-tup.mo
Labels: automerge-squash, cla:agreed

#3560 experimentally try using the GH-generated token
  .github/workflows/update-hash.yml
Labels: automerge-squash

#3561 chore: enable building `moc` on the M1
  nix/drun.nix
Labels: automerge-squash

#3556 Peephole optimizer: Eliminate get-set
  src/codegen/instrList.ml
  test/run/nested-multi-value.mo
Labels: automerge-squash, cla:agreed

#3566 Multi-value emulation: Use globals, not allocated tuples
  src/codegen/compile.ml
Labels: automerge-squash, cla:agreed

#3576 fix #3575
  doc/md/examples/grammar.txt
  src/gen-grammar/grammar.sed
  src/mo_frontend/source_lexer.mll
Labels: automerge-squash

#3587 chore: bump `peter-evans/*-comment` GH actions
  .github/workflows/test.yml
Labels: automerge-squash

#3586 bugfix: consider records with mutable fields non-static (fixes #3585)
  Changelog.md
  src/mo_frontend/static.ml
  test/fail/issue-3585/Field.mo
  test/fail/issue-3585/Object.mo
  test/fail/issue-3585/Record.mo
  test/fail/issue-3585a.mo
  test/fail/issue-3585b.mo
  test/fail/issue-3585c.mo
  test/fail/ok/issue-3585a.tc.ok
  test/fail/ok/issue-3585a.tc.ret.ok
  test/fail/ok/issue-3585b.tc.ok
  test/fail/ok/issue-3585b.tc.ret.ok
  test/fail/ok/issue-3585c.tc.ok
  test/fail/ok/issue-3585c.tc.ret.ok
Labels: automerge-squash

#3591 Building on the M1 works
  Building.md
Labels: automerge-squash

#3594 chore: fix up past `Changelog.md` entry
  Changelog.md
Labels: automerge-squash

#3599 fix: thread the mode into the parser
  src/languageServer/imports.ml
  src/mo_frontend/assertions.mly
  src/mo_frontend/parser.mly
  src/mo_frontend/parser_lib.ml
  src/mo_frontend/parsing.ml
  src/mo_frontend/parsing.mli
  src/pipeline/pipeline.ml
  test/fail/ok/verification-asserts.tc.ok
Labels: automerge-squash, viper

#3595 docs: example for `Array.equal`
  doc/md/base/Array.md
Labels: automerge-squash

#3455 Add source locations and exported types to `moc.js` parser output
  src/js/common.ml
  src/js/moc_interpreter.ml
  src/js/moc_js.ml
  src/mo_def/arrange.ml
  src/mo_types/type.ml
Labels: automerge-squash, tools

#3541 experiment: implement basic trampoline for moc ast interpreter
  src/ir_interpreter/interpret_ir.ml
  src/js/moc_interpreter.ml
  src/js/moc_js.ml
  src/mo_config/flags.ml
  src/mo_interpreter/interpret.ml
  src/mo_values/prim.ml
  src/mo_values/prim.mli
Labels: automerge-squash

#3601 Document `--viper` in `src/viper/README.md`
  README.md
  src/viper/README.md
Labels: viper

#3478 Reset type name counter for subsequent `moc.js` function calls
  src/js/common.ml
  src/mo_types/cons.ml
  src/mo_types/cons.mli
  test/test-moc.js
Labels: compiler, tools

#3495 Generational GC
  Changelog.md
  default.nix
  doc/md/compiler-ref.md
  rts/motoko-rts-tests/src/gc.rs
  rts/motoko-rts-tests/src/gc/compacting.rs
  rts/motoko-rts-tests/src/gc/compacting/mark_stack.rs
  rts/motoko-rts-tests/src/gc/generational.rs
  rts/motoko-rts-tests/src/gc/generational/mark_stack.rs
  rts/motoko-rts-tests/src/gc/heap.rs
  rts/motoko-rts-tests/src/gc/utils.rs
  rts/motoko-rts-tests/src/main.rs
  rts/motoko-rts-tests/src/remembered_set.rs
  rts/motoko-rts/src/blob_iter.rs
  rts/motoko-rts/src/continuation_table.rs
  rts/motoko-rts/src/gc.rs
  rts/motoko-rts/src/gc/generational.rs
  rts/motoko-rts/src/gc/generational/mark_stack.rs
  rts/motoko-rts/src/gc/generational/remembered_set.rs
  rts/motoko-rts/src/gc/generational/sanity_checks.rs
  rts/motoko-rts/src/gc/generational/write_barrier.rs
  rts/motoko-rts/src/text_iter.rs
  rts/motoko-rts/src/types.rs
  src/codegen/compile.ml
  src/exes/moc.ml
  src/js/common.ml
  src/mo_config/flags.ml
  test/bench/ok/palindrome.drun-run.ok
  test/run-drun/empty-actor.mo
  test/run-drun/free-callbacks.mo
  test/run-drun/rts-stats2.mo
Labels: automerge-squash

#3612 Fix bugs in memory sanity check of generational GC
  rts/motoko-rts/src/gc/generational/remembered_set.rs
  rts/motoko-rts/src/gc/generational/sanity_checks.rs
  test/run-drun/ok/text-iter-gc.drun-run.ok
  test/run-drun/ok/text-iter-gc.ic-ref-run.ok
  test/run-drun/ok/write-barrier-check.drun-run.ok
  test/run-drun/text-iter-gc.mo
  test/run-drun/write-barrier-check.mo
Labels: automerge-squash
