Repository dfinity/motoko, pull requests merged in 2022-08, with the labels that each got.

#3381 feat: record instruction costs of mutator and collector
  Changelog.md
  src/codegen/compile.ml
  src/mo_values/prim.ml
  src/prelude/prim.mo
  test/run-drun/empty-actor.mo
  test/run-drun/ok/rts_gc_instructions.drun-run.ok
  test/run-drun/rts_gc_instructions.mo
Labels: automerge-squash

#3396 Releasing 0.6.30
  Changelog.md
Labels: automerge-squash

#3397 Only consider minimised `*.min.js` files for the tarball
  release-files.nix
Labels: automerge-squash

#3367 alt syntax for record extension
  doc/md/examples/grammar.txt
  emacs/motoko-mode.el
  src/mo_frontend/error_reporting.ml
  src/mo_frontend/parser.mly
  src/mo_frontend/printers.ml
  src/mo_frontend/source_lexer.mll
  src/mo_frontend/source_token.ml
  test/fail/bad-obj-base.mo
  test/fail/check-record.mo
  test/fail/obj-empty-with.mo
  test/fail/obj-with.mo
  test/fail/ok/bad-obj-base.tc.ok
  test/fail/ok/check-record.tc.ok
  test/fail/ok/obj-empty-with.tc.ok
  test/fail/ok/obj-empty-with.tc.ret.ok
  test/repl/object-ext.sh
  test/run-drun/obj-ext-await.mo
  test/run/object-extend.mo
  test/run/objects-order.mo
Labels: automerge-squash

#3401 Add `difftastic` to the shell toolset
  default.nix
Labels: automerge-squash

#3409 Bump nixpkgs, without upgrading the Ocaml wasm library
  nix/default.nix
  nix/nix-build-uncached.nix
  nix/sources.json
  src/docs/.ocamlformat
  src/idllib/dune
  src/languageServer/.ocamlformat
  src/mo_frontend/dune
Labels: automerge-squash, cla:agreed

#3407 doc: describe typing and evaluation of record combination/extensions
  doc/md/language-manual.md
Labels: automerge-squash

#3386 feat: actor class management secondary class constructor and sugar
  Changelog.md
  doc/md/actor-classes.md
  doc/md/examples/grammar.txt
  doc/md/language-manual.md
  src/ir_def/construct.ml
  src/ir_def/construct.mli
  src/lowering/desugar.ml
  src/mo_frontend/parser.mly
  src/mo_frontend/typing.ml
  src/mo_interpreter/interpret.ml
  src/mo_types/type.ml
  src/mo_types/type.mli
  src/prelude/internals.mo
  test/fail/ok/illegal-await.tc.ok
  test/run-drun/actor-class-mgmt-interp.mo
  test/run-drun/actor-class-mgmt.mo
  test/run-drun/actor-class-mgmt/C.mo
  test/run-drun/map-upgrades.drun
  test/run-drun/map-upgrades/map0.mo
  test/run-drun/map-upgrades/map1.mo
  test/run-drun/map-upgrades/node0.mo
  test/run-drun/map-upgrades/node1.mo
  test/run-drun/ok/actor-class-mgmt-interp.diff-ir.ok
  test/run-drun/ok/actor-class-mgmt-interp.diff-low.ok
  test/run-drun/ok/actor-class-mgmt-interp.run-ir.ok
  test/run-drun/ok/actor-class-mgmt-interp.run-low.ok
  test/run-drun/ok/actor-class-mgmt-interp.run.ok
  test/run-drun/ok/actor-class-mgmt.drun-run.ok
  test/run-drun/ok/actor-class-mgmt.ic-ref-run.ok
  test/run-drun/ok/map-upgrades.drun.ok
  test/run-drun/ok/map-upgrades.ic-ref-run.ok
Labels: automerge-squash

#3375 Palindrome benchmark
  test/bench/ok/palindrome.drun-run.ok
  test/bench/ok/palindrome.tc.ok
  test/bench/palindrome.mo
Labels: automerge-squash

#3419 test: Assignment evaluation order
  test/run/assignment-order.mo
Labels: automerge-squash, testing

#3406 Backend: Avoid temporary variable in `set_val`
  src/codegen/compile.ml
  test/bench/ok/heap-32.drun-run.ok
Labels: automerge-squash, cla:agreed

#3423 Update `Changelog.md`
  Changelog.md
Labels: automerge-squash

#3425 Releasing 0.7.0
  Building.md
  Changelog.md
Labels: automerge-squash

#3430 Update `Building.md`, since base is tracking 0.7 now
  Building.md
Labels: automerge-squash

#3431 typofixes in explicit `import`
  doc/md/modules-and-imports.md
Labels: automerge-squash

#3435 chore: highlight new `with` keyword with hljs/ add to list of keyword in `doc`
  doc/docusaurus/src/theme/CodeBlock/hljs_run.js
  doc/md/language-manual.md
Labels: automerge-squash

#3436 Mention the Playground in the `README.md`
  README.md
Labels: automerge-squash
