Repository dfinity/motoko, pull requests merged in 2022-12, with the labels that each got.

#3619 feat: add doc comments to `moc.js` parse output
  src/js/common.ml
  src/mo_def/arrange.ml
  test/test-moc.js
Labels: automerge-squash, documentation, tools

#3623 hotfix: suppress GC in heartbeat
  Changelog.md
  src/codegen/compile.ml
Labels: automerge-squash

#3629 Releasing 0.7.4
  Changelog.md
Labels: automerge-squash

#3637 doc: fix for doc issue #3636 regaring await*
  doc/md/language-manual.md
Labels: automerge-squash

#3650 Add Blocks Editor to the readme under "Community resources"
  README.md
Labels: automerge-squash

#3657 chore: update "Build" status badge URL
  README.md
Labels: automerge-squash

#3665 chore: bump `rustc` stable to 1.66
  nix/default.nix
Labels: automerge-squash

#3666 chore: regenerate docs
  doc/md/base/Array.md
  doc/md/base/AssocList.md
  doc/md/base/Debug.md
  doc/md/base/Error.md
  doc/md/base/ExperimentalInternetComputer.md
  doc/md/base/Trie.md
  doc/md/base/TrieMap.md
  doc/md/base/index.md
Labels: automerge-squash

#3667 Releasing 0.7.5
  Changelog.md
Labels: automerge-squash

#3669 Docs: Indent the description of the <imp> production
  doc/md/language-manual.md
Labels: automerge-squash, cla:agreed
