Repository dfinity/motoko, pull requests merged in 2023-06, with the labels that each got.

#4015 chore: bump `nodejs` to v18
  default.nix
Labels: automerge-squash

#4009 Implement Prim.blobCompare
  src/codegen/compile.ml
  src/mo_values/prim.ml
  src/prelude/prim.mo
  test/run/text-compare.mo
Labels: automerge-squash, cla:agreed, build_artifacts

#4023 chore: reinstate the `ic-ref-run` test
  default.nix
  test/run-drun/ok/upgrades.ic-ref-run.ok
Labels: automerge-squash

#4027 feat: primitive for `ic0.canister_version`
  Changelog.md
  src/codegen/compile.ml
  src/mo_values/prim.ml
  src/prelude/prim.mo
  test/run-drun/empty-actor.mo
  test/run-drun/ok/upgrades.drun.ok
  test/run-drun/ok/upgrades.ic-ref-run.ok
  test/run-drun/upgrades/upgrade0.mo
  test/run-drun/upgrades/upgrade1.mo
Labels: feature, automerge-squash, canisters

#4012 temporary: no `or`-pattern inference
  src/lang_utils/error_codes.ml
  src/mo_frontend/typing.ml
  test/fail/ok/or-pattern-infer.tc.ok
  test/fail/ok/or-pattern-infer.tc.ret.ok
  test/fail/ok/pat-inconsistent.tc.ok
  test/fail/or-pattern-infer.mo
  test/fail/pat-inconsistent.mo
  test/run/coverage.mo
  test/run/ok/coverage.tc.ok
Labels: automerge-squash

#4029 chore: update docs
  doc/md/base/Principal.md
Labels: automerge-squash

#4028 chore: Releasing 0.9.2
  Changelog.md
Labels: automerge-squash

#4030 Update `Building.md`
  Building.md
Labels: automerge-squash

#4031 chore: state the credits
  Changelog.md
Labels: automerge-squash

#4018 fix(mo-doc): show help menu when passing unexpected positional arg
  src/exes/mo_doc.ml
Labels: automerge-squash

#4043 chore: perform scheduled builds of `drun` in a sparse artefact environment
  .github/workflows/test.yml
  default.nix
Labels: automerge-squash

#4046 chore: `obelisk` is at toplevel, remove customisation
  default.nix
  nix/default.nix
  nix/ocaml-obelisk.nix
Labels: automerge-squash

#4048 chore: use non-deprecated flags when building RTS
  rts/Makefile
Labels: automerge-squash

#4047 chore: bump `install-nix-action` to v22
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-hash.yml
Labels: automerge-squash

#4024 Incremental GC: Fix the live set computation
  rts/motoko-rts/src/gc/incremental.rs
Labels: Bug, automerge-squash

#4052 chore: docs update
  doc/md/base/Blob.md
Labels: automerge-squash

#4051 chore: Releasing 0.9.3
  Changelog.md
Labels: automerge-squash

#4055 chore: remove unnecessary `ppx` dependencies
  default.nix
Labels: automerge-squash

#4042 bugfix: allow optional terminal semicolons in Candid imports
  Changelog.md
  src/idllib/arrange_idl.ml
  src/idllib/parser.mly
  test/idl/ok/semi-test.js.ok
  test/idl/semi-test.did
Labels: automerge-squash

#4041 feat: allow canister imports of service constructors, silently ignoring the service arguments.
  Changelog.md
  src/lang_utils/error_codes.ml
  src/mo_idl/idl_to_mo.ml
  test/run-drun/issue-2319.mo
  test/run-drun/ok/issue-2319.tc.ok
  test/run-drun/ok/issue-2319.tc.ret.ok
  test/run-drun/ok/service-import.drun-run.ok
  test/run-drun/ok/service-import.ic-ref-run.ok
  test/run-drun/ok/service-import.tc.ok
  test/run-drun/service-import.mo
  test/run-drun/service-import/rwlgt-iiaaa-aaaaa-aaaaa-cai.did
Labels: automerge-squash

#4063 bugfix: issue #4054 (treat negative float literals as static)
  src/mo_frontend/parser.mly
  test/run/issue-4054.mo
Labels: automerge-squash

#4065 Fix typo in IDL-Motoko.md
  design/IDL-Motoko.md
Labels: automerge-squash

#3953 chore: `nix-build-uncached` problem is resolved, building in `nix`-2.15
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-hash.yml
Labels: automerge-squash

#4073 chore: update changelog
  Changelog.md
Labels: automerge-squash

#4021 Incremental GC: Optimize occupied size computation
  rts/motoko-rts/src/gc/incremental/partitioned_heap.rs
Labels: automerge-squash, performance

#4083 refactor: deduplicate two functions
  src/codegen/compile.ml
  src/linking/linkModule.ml
Labels: automerge-squash

#4003 feat: composite queries
  Changelog.md
  doc/docusaurus/src/theme/CodeBlock/hljs_run.js
  doc/md/actors-async.md
  doc/md/examples/CompositeSemantics.mo
  doc/md/examples/CounterWithCompositeQuery.mo
  doc/md/examples/grammar.txt
  doc/md/language-manual.md
  doc/md/message-inspection.md
  rts/motoko-rts/src/idl.rs
  src/codegen/compile.ml
  src/docs/html.ml
  src/docs/plain.ml
  src/gen-grammar/grammar.sed
  src/idllib/arrange_idl.ml
  src/idllib/compile_js.ml
  src/idllib/escape.ml
  src/idllib/lexer.mll
  src/idllib/parser.mly
  src/idllib/syntax.ml
  src/ir_def/check_ir.ml
  src/lang_utils/error_codes.ml
  src/mo_def/arrange.ml
  src/mo_frontend/error_reporting.ml
  src/mo_frontend/parser.mly
  src/mo_frontend/printers.ml
  src/mo_frontend/source_lexer.mll
  src/mo_frontend/source_token.ml
  src/mo_frontend/typing.ml
  src/mo_idl/mo_to_idl.ml
  src/mo_types/arrange_type.ml
  src/mo_types/async_cap.ml
  src/mo_types/typ_hash.ml
  src/mo_types/type.ml
  src/mo_types/type.mli
  src/prelude/internals.mo
  test/fail/composite-query-fail.mo
  test/fail/ok/bad-call-raw.tc.ok
  test/fail/ok/composite-query-fail.tc.ok
  test/fail/ok/composite-query-fail.tc.ret.ok
  test/fail/ok/queries.tc.ok
  test/run-drun/composite-inspect-message.mo
  test/run-drun/composite-query.mo
  test/run-drun/composite-query/Class.mo
  test/run-drun/composite-semantics.mo
  test/run-drun/idl-composite.mo
  test/run-drun/ok/composite-inspect-message.drun-run.ok
  test/run-drun/ok/composite-inspect-message.ic-ref-run.ok
  test/run-drun/ok/composite-query.drun-run.ok
  test/run-drun/ok/composite-query.tc.ok
  test/run-drun/ok/composite-semantics.drun-run.ok
  test/run-drun/ok/idl-composite.drun-run.ok
Labels: automerge-squash

#3987 feat: pipe operator and placeholder expression
  Changelog.md
  doc/md/examples/Piped.mo
  doc/md/examples/Unpiped.mo
  doc/md/examples/grammar.txt
  doc/md/language-manual.md
  doc/md/pipes.md
  src/gen-grammar/grammar.sed
  src/mo_frontend/error_reporting.ml
  src/mo_frontend/parser.mly
  src/mo_frontend/printers.ml
  src/mo_frontend/source_lexer.mll
  src/mo_frontend/source_token.ml
  test/fail/ok/pipe-ill-typed.tc.ok
  test/fail/ok/pipe-ill-typed.tc.ret.ok
  test/fail/ok/syntax2.tc.ok
  test/fail/ok/syntax3.tc.ok
  test/fail/ok/syntax5.tc.ok
  test/fail/pipe-ill-typed.mo
  test/run/ok/pipes.run-ir.ok
  test/run/ok/pipes.run-low.ok
  test/run/ok/pipes.run.ok
  test/run/ok/pipes.tc.ok
  test/run/ok/pipes.wasm-run.ok
  test/run/pipes.mo
Labels: automerge-squash

#4002 bugfix: improve error message to include object fields
  src/mo_frontend/typing.ml
  test/fail/ok/no-timer-canc.tc.ok
  test/fail/ok/no-timer-set.tc.ok
Labels: automerge-squash

#3995 feat: multiline `Text` literals
  Changelog.md
  doc/md/language-manual.md
  src/mo_frontend/source_lexer.mll
  test/fail/multiline-text-line-number.mo
  test/fail/ok/multiline-text-line-number.tc.ok
  test/fail/ok/multiline-text-line-number.tc.ret.ok
  test/repl/ok/stateful.stderr.ok
  test/repl/stateful.sh
  test/run/ok/text-multiline.run-ir.ok
  test/run/ok/text-multiline.run-low.ok
  test/run/ok/text-multiline.run.ok
  test/run/ok/text-multiline.wasm-run.ok
  test/run/text-multiline.mo
  test/run/text-pats.mo
Labels: automerge-squash

#4089 chore: doc updates
  doc/md/base/Array.md
  doc/md/base/Text.md
Labels: automerge-squash
