Repository dfinity/motoko, pull requests merged in 2023-03, with the labels that each got.

#3850 bump `install-nix-action` to v20
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-hash.yml
Labels: automerge-squash

#3853 Backend: Avoid pointless bounds checking array access
  src/codegen/compile.ml
Labels: automerge-squash, cla:agreed

#3860 fix call to region_init
  src/codegen/compile.ml
Labels: DO-NOT-MERGE

#3863 Optimize `array.size()`, `blob.size()` and `text.size()`
  src/codegen/compile.ml
  src/ir_def/construct.ml
  src/ir_def/construct.mli
  src/lowering/desugar.ml
  test/run/array-len.mo
  test/run/ok/array-len.run-ir.ok
  test/run/ok/array-len.run-low.ok
  test/run/ok/array-len.run.ok
  test/run/ok/array-len.wasm-run.ok
  test/run/ok/idl-ops.wasm-run.ok
  test/run/ok/idl.wasm-run.ok
Labels: automerge-squash, cla:agreed

#3865 Support multi-value and unboxed returns from switch statement
  src/codegen/compile.ml
  test/bench/ok/palindrome.drun-run.ok
  test/run/multi-value-block.mo
  test/run/switch-trap.mo
Labels: automerge-squash, cla:agreed, opportunity

#3869 grammar fix for `let-else`
  doc/md/examples/grammar.txt
  src/mo_frontend/parser.mly
  test/run/let-else-if.mo
Labels: automerge-squash

#3873 perf: peephole-optimise `const 1; and; if t e` to `ctz; if e t`
  src/codegen/instrList.ml
  test/bench/ok/alloc.drun-run.ok
  test/bench/ok/heap-32.drun-run.ok
  test/bench/ok/palindrome.drun-run.ok
  test/run-drun/ok/perf.drun-run.ok
Labels: automerge-squash, opportunity

#3870 chore: better spacing for `timer.mo` test
  test/run-drun/ok/timer.drun-run.ok
  test/run-drun/ok/timer.ic-ref-run.ok
  test/run-drun/timer.mo
Labels: automerge-squash

#3876 Releasing 0.8.4
  Changelog.md
Labels: automerge-squash

#3878 perf: identify const variants
  src/codegen/compile.ml
  src/ir_def/check_ir.ml
  src/ir_passes/const.ml
Labels: automerge-squash

#3867 backend: Push expected stackrep into branches of `IfE` and `SwitchE`
  src/codegen/compile.ml
  test/compare-wat.sh
  test/run/multi-value-block.mo
Labels: automerge-squash, cla:agreed

#3882 doc: fix definition of subtyping of object types in `language-manual.md`
  doc/md/language-manual.md
Labels: automerge-squash

#3883 bugfix: check `@nextExpiration` after the changes are committed
  src/prelude/internals.mo
Labels: automerge-squash

#3885 chore: regenerate base documentation
  doc/md/base/Array.md
  doc/md/base/Trie.md
  doc/md/base/TrieMap.md
Labels: automerge-squash

#3886 Releasing 0.8.5
  Changelog.md
Labels: automerge-squash

#3888 Backend: `trap` PrimOP does not return
  src/codegen/compile.ml
  test/run/issue3887.mo
Labels: automerge-squash, cla:agreed

#3889 chore: update `Building.md`
  Building.md
Labels: automerge-squash

#3866 CI: Run ic-ref-run only once
  default.nix
Labels: automerge-squash, cla:agreed

#3897 Refactor: Common up array indexing code
  src/codegen/compile.ml
Labels: automerge-squash, cla:agreed

#3901 bugfix: compiler crash when matching on constant variants
  src/codegen/compile.ml
  test/run/ok/refuted-const-variant.run.ok
  test/run/ok/refuted-const-variant.run.ret.ok
  test/run/ok/refuted-const-variant.tc.ok
  test/run/ok/refuted-const-variant.wasm-run.ok
  test/run/ok/refuted-const-variant.wasm-run.ret.ok
  test/run/refuted-const-variant.mo
  test/run/variants.mo
Labels: automerge-squash, opportunity
