Repository dfinity/motoko, pull requests merged in 2023-04, with the labels that each got.

#3909 Releasing 0.8.6
  Changelog.md
Labels: automerge-squash

#3871 feat: when re-adding recurrent timers, skip over past expirations
  src/prelude/internals.mo
Labels: automerge-squash

#3917 perf: improve `cyclesAdd`
  src/prelude/prim.mo
Labels: automerge-squash, opportunity

#3918 feat(mo-doc): nested modules
  doc/md/base/Trie.md
  src/docs/adoc.ml
  src/docs/extract.ml
  src/docs/html.ml
  src/docs/plain.ml
Labels: automerge-squash, documentation

#3922 chore: document `base` doc update step
  Building.md
Labels: automerge-squash

#3923 Releasing 0.8.7
  Changelog.md
Labels: automerge-squash

#3933 chore: specify `nix` version on CI by pinning v2.13.3
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/update-hash.yml
Labels: automerge-squash

#3934 chore: fix `update-hash`
  .github/workflows/update-hash.yml
Labels: automerge-squash

#3945 chore: bump `rustc` stable to 1.66.1
  nix/default.nix
Labels: automerge-squash

#3948 chore: simplify `base-src` derivation
  default.nix
Labels: automerge-squash

#3949 chore: reference a PR's branch that fixes Darwin
  nix/sources.json
Labels: automerge-squash

#3952 chore: bump `rustc` stable to v1.69
  nix/default.nix
  nix/drun.nix
Labels: automerge-squash

#3954 chore: show failed tests only once
  test/run.sh
Labels: automerge-squash

#3958 perf: `If`-related peephole rules
  src/codegen/instrList.ml
  test/run/empty-if.mo
  test/run/issue1356.mo
Labels: automerge-squash

#3957 perf: improve codegen for `?_` and `#variant _` (and also `()`)
  src/codegen/compile.ml
  src/ir_def/ir_utils.ml
Labels: automerge-squash
