Repository dfinity/motoko, pull requests merged in 2023-07, with the labels that each got.

#4090 chore: Releasing 0.9.4
  Changelog.md
Labels: automerge-squash

#3997 chore: change binary release artefact names
  release-files.nix
Labels: automerge-squash

#3807 feat: bindings in `or`-patterns
  Changelog.md
  design/WhitePaper.md
  doc/md/language-manual.md
  src/ir_def/check_ir.ml
  src/ir_def/freevars.ml
  src/ir_interpreter/interpret_ir.ml
  src/ir_passes/const.ml
  src/ir_passes/tailcall.ml
  src/lang_utils/error_codes.ml
  src/lib/lib.ml
  src/lib/lib.mli
  src/mo_frontend/definedness.ml
  src/mo_frontend/typing.ml
  src/mo_interpreter/interpret.ml
  test/fail/M0105.mo
  test/fail/ok/M0105.tc.ok
  test/fail/ok/or-pattern-diff.tc.ok
  test/fail/ok/or-pattern-diff.tc.ret.ok
  test/fail/or-pattern-diff.mo
  test/run/ok/or-pattern-binds.run-ir.ok
  test/run/ok/or-pattern-binds.run-low.ok
  test/run/ok/or-pattern-binds.run.ok
  test/run/ok/or-pattern-binds.tc.ok
  test/run/ok/or-pattern-binds.wasm-run.ok
  test/run/ok/or-pattern-mismatch.tc.ok
  test/run/or-pattern-binds.mo
  test/run/or-pattern-mismatch.mo
Labels: feature, automerge-squash

#4064 perf: keep the heap pointer in a dedicated Wasm global
  Changelog.md
  rts/motoko-rts/src/gc.rs
  rts/motoko-rts/src/gc/copying.rs
  rts/motoko-rts/src/gc/generational.rs
  rts/motoko-rts/src/gc/mark_compact.rs
  rts/motoko-rts/src/memory/ic/linear_memory.rs
  src/codegen/compile.ml
  test/bench/ok/alloc.drun-run.ok
  test/bench/ok/heap-32.drun-run.ok
  test/bench/ok/palindrome.drun-run.ok
Labels: automerge-squash, performance, opportunity

#4099 chore: Releasing 0.9.5
  Changelog.md
Labels: automerge-squash

#4095 perf: keep a skewed pointer in `HP`
  rts/motoko-rts-tests/Cargo.lock
  rts/motoko-rts-tests/src/gc.rs
  rts/motoko-rts/src/barriers.rs
  rts/motoko-rts/src/gc.rs
  rts/motoko-rts/src/gc/copying.rs
  rts/motoko-rts/src/gc/generational.rs
  rts/motoko-rts/src/gc/generational/write_barrier.rs
  rts/motoko-rts/src/gc/incremental.rs
  rts/motoko-rts/src/gc/mark_compact.rs
  rts/motoko-rts/src/memory/ic.rs
  rts/motoko-rts/src/memory/ic/linear_memory.rs
  src/codegen/compile.ml
  test/bench/ok/alloc.drun-run.ok
  test/bench/ok/heap-32.drun-run.ok
  test/bench/ok/palindrome.drun-run.ok
Labels: automerge-squash

#4103 feat: allow controllers to call `__motoko_stable_var_info` query endpoint
  Changelog.md
  src/ir_def/construct.ml
  src/lowering/desugar.ml
  test/run-drun/ok/query-footprint.drun-run.ok
  test/run-drun/ok/query-footprint.ic-ref-run.ok
Labels: automerge-squash, opportunity

#4106 Remove reference to global maps
  src/mo_idl/mo_to_idl.ml
Labels: automerge-squash, build_artifacts

#4110 chore: Releasing 0.9.6
  Changelog.md
Labels: automerge-squash

#3972 fix: converting example variants to proper case
  doc/md/overview.md
Labels: automerge-squash, cla:agreed

#3963 chore: import a small(ish) DAO app
  test/perf/assetstorage/AssocList.mo
  test/perf/assetstorage/Blob.mo
  test/perf/assetstorage/Debug.mo
  test/perf/assetstorage/ExperimentalInternetComputer.mo
  test/perf/assetstorage/Int.mo
  test/perf/assetstorage/Principal.mo
  test/perf/assetstorage/Time.mo
  test/perf/assetstorage/Trie.mo
  test/perf/dao.mo
  test/perf/dao/dao-types.mo
  test/perf/ok/dao.drun-run.ok
  test/perf/ok/dao.tc.ok
Labels: automerge-squash

#4116 chore: bump `add-and-commit` action
  .github/workflows/update-hash.yml
Labels: automerge-squash

#4109 chore: pull in the `ic-wasm` tool
  .github/workflows/niv-updater-rare.yml
  .github/workflows/niv-updater-trial.yml
  .github/workflows/update-hash.yml
  default.nix
  nix/sources.json
  test/bench/ok/alloc.drun-run-opt.ok
  test/bench/ok/heap-32.drun-run-opt.ok
  test/bench/ok/palindrome.drun-run-opt.ok
  test/run.sh
Labels: automerge-squash

#4115 chore: delete obsolete script
  add-tags.sh
Labels: automerge-squash

#4118 chore: `nix` gardening
  ci.nix
  default.nix
  nix/default.nix
  nix/generate.nix
Labels: automerge-squash

#4096 perf: extend the overflow detection mask to the right if the bump increment is a power of 2
  src/codegen/compile.ml
  test/bench/ok/alloc.drun-run-opt.ok
  test/bench/ok/alloc.drun-run.ok
  test/bench/ok/heap-32.drun-run-opt.ok
  test/bench/ok/heap-32.drun-run.ok
Labels: automerge-squash

#4123 chore: work around `heartbeat`-related flakiness in `dao.mo` by voting twice
  test/perf/dao.mo
  test/perf/ok/dao.drun-run.ok
Labels: automerge-squash

#4025 chore: add contribution info to `README.md`
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
Labels: automerge-squash

#4122 benchmark: bench `Nat16` arithmetic
  test/bench/nat16.mo
  test/bench/ok/nat16.drun-run-opt.ok
  test/bench/ok/nat16.drun-run.ok
Labels: automerge-squash

#4128 bugfix: support import of Candid composite queries
  Changelog.md
  src/mo_idl/idl_to_mo.ml
  test/run-drun/composite-import.mo
  test/run-drun/composite-import/rwlgt-iiaaa-aaaaa-aaaaa-cai.did
  test/run-drun/ok/composite-import.drun-run.ok
  test/run-drun/ok/composite-import.tc.ok
Labels: automerge-squash

#4131 chore: Releasing 0.9.7
  Changelog.md
Labels: automerge-squash

#4111 chore: don't create legacy-named release artefacts
  release-files.nix
Labels: automerge-squash

#4138 test: extracting argument 0 as a tuple
  default.nix
  test/run/candid.mo
Labels: automerge-squash

#4153 Building.md: Improve nix-env instructions
  Building.md
Labels: automerge-squash, cla:agreed
