Repository dfinity/motoko, pull requests merged in 2024-10, with the labels that each got.

#4714 feat: check restriction on main actor before type checking
  src/lang_utils/error_codes.ml
  src/lang_utils/error_codes/M0141.md
  src/mo_frontend/typing.ml
  src/mo_frontend/typing.mli
  src/pipeline/pipeline.ml
  src/pipeline/pipeline.mli
  test/run-drun/bad-actor.mo
  test/run-drun/ok/bad-actor.comp-ref.ok
  test/run-drun/ok/bad-actor.comp-ref.ret.ok
  test/run-drun/ok/bad-actor.comp.ok
  test/run-drun/ok/bad-actor.comp.ret.ok
  test/run-drun/ok/issue-1938-b.comp-ref.ok
  test/run-drun/ok/issue-1938-b.comp.ok
  test/run-drun/ok/issue-1938-c.comp-ref.ok
  test/run-drun/ok/issue-1938-c.comp.ok
  test/run-drun/ok/issue-1938-d.comp-ref.ok
  test/run-drun/ok/issue-1938-d.comp.ok
  test/run-drun/ok/issue-1938.comp-ref.ok
  test/run-drun/ok/issue-1938.comp.ok
  test/run-drun/ok/unavailable-constructor.comp-ref.ok
  test/run-drun/ok/unavailable-constructor.comp.ok
  test/run-drun/ok/unavailable-constructor.tc.ok
  test/run-drun/ok/unsupported-more.comp-ref.ok
  test/run-drun/ok/unsupported-more.comp.ok
  test/run-drun/ok/unsupported.comp-ref.ok
  test/run-drun/ok/unsupported.comp.ok
  test/run-drun/ok/unsupported.tc.ok
  test/run-drun/unavailable-constructor.mo
  test/run-drun/unsupported.mo
Labels: automerge-squash

#4720 feat: suggest corrections for unbound identifiers/fields based on distance metric
  Changelog.md
  doc/md/reference/compiler-ref.md
  src/exes/moc.ml
  src/lib/lib.ml
  src/lib/lib.mli
  src/mo_config/flags.ml
  src/mo_frontend/typing.ml
  src/mo_types/type.ml
  src/prelude/internals.mo
  test/fail/ok/M0028.tc.ok
  test/fail/ok/bad-type-comp.tc.ok
  test/fail/ok/modexp1.tc.ok
  test/fail/ok/pretty.tc.ok
  test/fail/ok/suggest-label-ai.tc.ok
  test/fail/ok/suggest-label-ai.tc.ret.ok
  test/fail/ok/suggest-label.tc.ok
  test/fail/ok/suggest-label.tc.ret.ok
  test/fail/ok/suggest-local-ai.tc.ok
  test/fail/ok/suggest-local-ai.tc.ret.ok
  test/fail/ok/suggest-local-type-ai.tc.ok
  test/fail/ok/suggest-local-type-ai.tc.ret.ok
  test/fail/ok/suggest-local-type.tc.ok
  test/fail/ok/suggest-local-type.tc.ret.ok
  test/fail/ok/suggest-local.tc.ok
  test/fail/ok/suggest-local.tc.ret.ok
  test/fail/ok/suggest-long-ai.tc.ok
  test/fail/ok/suggest-long-ai.tc.ret.ok
  test/fail/ok/suggest-long.tc.ok
  test/fail/ok/suggest-long.tc.ret.ok
  test/fail/ok/suggest-short-ai.tc.ok
  test/fail/ok/suggest-short-ai.tc.ret.ok
  test/fail/ok/suggest-short.tc.ok
  test/fail/ok/suggest-short.tc.ret.ok
  test/fail/ok/suggest-type-ai.tc.ok
  test/fail/ok/suggest-type-ai.tc.ret.ok
  test/fail/ok/suggest-type.tc.ok
  test/fail/ok/suggest-type.tc.ret.ok
  test/fail/suggest-label-ai.mo
  test/fail/suggest-label.mo
  test/fail/suggest-local-ai.mo
  test/fail/suggest-local-type-ai.mo
  test/fail/suggest-local-type.mo
  test/fail/suggest-local.mo
  test/fail/suggest-long-ai.mo
  test/fail/suggest-long.mo
  test/fail/suggest-short-ai.mo
  test/fail/suggest-short.mo
  test/fail/suggest-type-ai.mo
  test/fail/suggest-type.mo
Labels: automerge-squash

#4662 doc: candid serialization and raw calls
  doc/md/writing-motoko/candid.md
Labels: automerge-squash

#4725 docs: remove extra `mops install` from `dev-env.md`
  doc/md/getting-started/dev-env.md
Labels: external-contributor

#4728 chore: skip redundant `repl` test on CI
  default.nix
Labels: automerge-squash, testing

#4683 Use Custom Rust Targets for Shared Wasm Libraries
  .github/workflows/niv-updater-rare.yml
  .github/workflows/niv-updater-trial.yml
  .github/workflows/niv-updater.yml
  default.nix
  nix/default.nix
  nix/sources.json
  rts/Makefile
  rts/motoko-rts/config.toml
  rts/motoko-rts/src/allocator.rs
  rts/motoko-rts/src/libc_declarations.rs
  rts/motoko-rts/wasm32-unknown-shared.json
  rts/motoko-rts/wasm64-unknown-shared.json
  rts/stubs.c
  src/codegen/compile_classical.ml
  src/codegen/compile_enhanced.ml
  src/linking/linkModule.ml
  test/bench/ok/bignum.drun-run.ok
  test/bench/ok/candid-subtype-cost.drun-run.ok
  test/bench/ok/heap-32.drun-run.ok
  test/bench/ok/heap-64.drun-run.ok
  test/ld/Makefile
  test/ld/ok/fun-ptr.linked.wat.ok
  test/ld/ok/representative.linked.wat.ok
Labels: dependencies

#4730 chore: fix mergify warnings
  .mergify.yml
Labels: automerge-squash

#4679 Test Canister Snapshots
  nix/sources.json
  test/run-drun/ok/snapshot.drun-run.ok
  test/run-drun/snapshot.mo
  test/run-drun/snapshot/test-actor.mo
Labels: automerge-squash, testing

#4719 feat: allow access to `Self` and its public methods from `actor` initialisers
  Changelog.md
  src/ir_interpreter/interpret_ir.ml
  src/lib/lib.mli
  src/lowering/desugar.ml
  src/mo_def/arrange.ml
  src/mo_def/compUnit.ml
  src/mo_def/syntax.ml
  src/mo_frontend/definedness.ml
  src/mo_frontend/parser.mly
  src/mo_frontend/typing.ml
  src/mo_interpreter/interpret.ml
  src/mo_values/operator.ml
  src/mo_values/prim.ml
  src/viper/traversals.ml
  test/run-drun/incomplete-self-reference.mo
  test/run-drun/ok/incomplete-self-reference.drun-run.ok
  test/run-drun/ok/incomplete-self-reference.run-ir.ok
  test/run-drun/ok/incomplete-self-reference.run-low.ok
  test/run-drun/ok/incomplete-self-reference.run.ok
  test/run-drun/ok/pass-class-self.diff-ir.ok
  test/run-drun/ok/pass-class-self.diff-low.ok
  test/run-drun/ok/pass-class-self.drun-run.ok
  test/run-drun/ok/pass-class-self.run-ir.ok
  test/run-drun/ok/pass-class-self.run-low.ok
  test/run-drun/ok/pass-class-self.tc.ok
  test/run-drun/ok/pass-self.drun-run.ok
  test/run-drun/ok/pass-self.run-ir.ok
  test/run-drun/ok/pass-self.run-low.ok
  test/run-drun/ok/pass-self.run.ok
  test/run-drun/pass-class-self.mo
  test/run-drun/pass-self.mo
Labels: automerge-squash

#4737 chore: Releasing 0.13.2
  Changelog.md
Labels: automerge-squash
