Repository dfinity/motoko, pull requests merged in 2024-07, with the labels that each got.

#4587 Refine the Memory Reserve Handling in the Allocator
  rts/motoko-rts/src/memory/ic.rs
Labels: automerge-squash

#4597 Make CI Performance Comparison Test Deterministic
  test/perf/dao.mo
  test/perf/ok/dao.drun-run.ok
Labels: automerge-squash

#4603 chore: Releasing 0.11.2
  Changelog.md
Labels: automerge-squash

#4606 chore: tweak `Changelog.md`
  Changelog.md
Labels: automerge-squash

#4600 Allow `try` without `catch`
  src/ir_passes/await.ml
  src/lib/lib.ml
  src/lib/lib.mli
  src/mo_frontend/parser.mly
  test/run-drun/ok/try-finally.drun-run.ok
  test/run-drun/ok/try-finally.run-ir.ok
  test/run-drun/ok/try-finally.run-low.ok
  test/run-drun/ok/try-finally.run.ok
  test/run-drun/ok/try-finally.tc.ok
  test/run-drun/try-finally.mo
Labels: opportunity

#4609 copy-paste error: arrange `SystemCyclesAddPrim`
  src/ir_def/arrange_ir.ml
Labels: automerge-squash

#4576 Code Refactoring: Unifying `ObjInd` and `MutBox`
  rts/motoko-rts-tests/src/gc/compacting/mark_stack.rs
  rts/motoko-rts/src/debug.rs
  rts/motoko-rts/src/static_checks.rs
  rts/motoko-rts/src/types.rs
  rts/motoko-rts/src/visitor.rs
  src/codegen/compile.ml
Labels: automerge-squash

#4594 DD-221: document option blocks, record extension, `system` capabilities and `let`/`else`
  doc/md/getting-started/basic-concepts.md
  doc/md/writing-motoko/pattern-matching.md
Labels: automerge-squash, documentation

#4619 chore: Releasing 0.11.3
  Changelog.md
Labels: automerge-squash

#4611 IR: don't create unnecessary variable renaming for the sake of `NewObjE`
  src/ir_def/check_ir.ml
  src/ir_def/construct.ml
  src/ir_interpreter/interpret_ir.ml
  src/lowering/desugar.ml
  test/run-drun/4611.mo
  test/run-drun/ok/4611.drun-run.ok
  test/run-drun/ok/4611.run-ir.ok
  test/run-drun/ok/4611.run-low.ok
  test/run-drun/ok/4611.run.ok
Labels: automerge-squash, enhancement

#4623 bug: `NewObjE` initialisation short-circuiting with mutable variables is changing behaviour
  src/ir_def/check_ir.ml
  src/ir_def/construct.ml
  src/ir_interpreter/interpret_ir.ml
  src/lowering/desugar.ml
  test/run-drun/4611.mo
  test/run-drun/ok/4611.drun-run.ok
  test/run-drun/ok/4611.run-ir.ok
  test/run-drun/ok/4611.run-low.ok
  test/run-drun/ok/4611.run.ok
Labels: automerge-squash

#4585 EOP: Support Unknown Main Memory Capacity in 64-Bit
  rts/motoko-rts-tests/src/gc.rs
  rts/motoko-rts-tests/src/gc/incremental/partitioned_heap.rs
  rts/motoko-rts-tests/src/memory.rs
  rts/motoko-rts/src/gc/incremental.rs
  rts/motoko-rts/src/gc/incremental/partitioned_heap.rs
  rts/motoko-rts/src/gc/incremental/scheduling.rs
  rts/motoko-rts/src/memory/ic.rs
  rts/motoko-rts/src/persistence.rs
  rts/motoko-rts/src/types.rs
  src/codegen/compile.ml
  test/bench/ok/alloc.drun-run.ok
  test/bench/ok/heap-32.drun-run.ok
  test/bench/ok/heap-64.drun-run.ok
Labels: enhancement

#4612 doc: revisions
  doc/md/getting-started/basic-concepts.md
  doc/md/writing-motoko/control-flow.md
  doc/md/writing-motoko/local-objects-classes.md
  doc/md/writing-motoko/pattern-matching.md
  doc/md/writing-motoko/system-capability.md
Labels: automerge-squash

#4627 chore: add Motoko logo to `README.md`
  README.md
Labels: automerge-squash

#4626 fix(mo-doc): include public variables in generated docs
  src/docs/adoc.ml
  src/docs/extract.ml
  src/docs/html.ml
  src/docs/plain.ml
Labels: tools

#4618 chore: update docs
  doc/md/base/Float.md
Labels: automerge-squash, documentation

#4634 chore: Releasing 0.12.0
  Changelog.md
Labels: automerge-squash

#4635 `__motoko_runtime_information()` as Privileged Query for Runtime Statistics.
  Changelog.md
  src/ir_def/construct.ml
  src/lowering/desugar.ml
  src/mo_types/type.ml
  src/mo_types/type.mli
  test/bench/ok/bignum.drun-run-opt.ok
  test/bench/ok/heap-32.drun-run-opt.ok
  test/bench/ok/heap-32.drun-run.ok
  test/bench/ok/palindrome.drun-run-opt.ok
  test/bench/ok/palindrome.drun-run.ok
  test/run-drun/ok/runtime-info-acl.drun-run.ok
  test/run-drun/ok/runtime-info.drun-run.ok
  test/run-drun/runtime-info-acl.mo
  test/run-drun/runtime-info-acl/C.mo
  test/run-drun/runtime-info.mo
  test/run-drun/runtime-info/info.mo
Labels: automerge-squash, debugging

#4641 test: testing ability to upgrade after trapping finally
  doc/md/reference/language-manual.md
  test/run-drun/ok/try-finally-trap-stop.drun-run.ok
  test/run-drun/ok/try-finally-trap.drun.ok
  test/run-drun/try-finally-trap-stop.mo
  test/run-drun/try-finally-trap-stop/class.mo
  test/run-drun/try-finally-trap.drun
  test/run-drun/try-finally-trap/try-finally-trap.mo
Labels: automerge-squash
