Repository dfinity/motoko, pull requests merged in 2024-09, with the labels that each got.

#4678 chore: Upgrade `drun`
  nix/drun.nix
  nix/sources.json
Labels: automerge-squash, dependencies

#4685 Fix: Start Wasm table for the RTS at offset >= 1
  src/linking/linkModule.ml
  test/ld/ok/representative.linked.wat.ok
Labels: Bug, automerge-squash

#4669 doc: add `try`/`finally` code example
  doc/md/examples/try-finally.mo
  doc/md/writing-motoko/errors.md
Labels: automerge-squash

#4696 chore: regenerate documentation
  doc/md/base/Iter.md
Labels: automerge-squash

#4690 feat: burning cycles programmatically
  Building.md
  Changelog.md
  src/codegen/compile_classical.ml
  src/codegen/compile_enhanced.ml
  src/ir_def/arrange_ir.ml
  src/ir_def/check_ir.ml
  src/ir_def/construct.ml
  src/ir_def/ir.ml
  src/lowering/desugar.ml
  src/prelude/prim.mo
  test/fail/ok/no-timer-canc.tc.ok
  test/fail/ok/no-timer-set.tc.ok
  test/run-drun/basic-cycles.mo
  test/run-drun/empty-actor-classical.mo
  test/run-drun/ok/basic-cycles.tc.ok
Labels: feature, automerge-squash

#4697 chore: Releasing 0.13.0
  Changelog.md
Labels: automerge-squash

#4699 chore: bump `nixpkgs` to `release-24.05`
  default.nix
  nix/emscripten-fix.patch
  nix/sources.json
  src/docs/.ocamlformat
  src/languageServer/.ocamlformat
  test/lsp-int/lsp-int.cabal
  test/random/qc-motoko.cabal
Labels: automerge-squash

#4700 chore: Releasing 0.13.0
  Changelog.md
Labels: automerge-squash

#4712 fix: reproduce and fix `motoko-base/issues/653`
  src/mo_values/numerics.ml
  test/run/issue-base653.mo
Labels: Bug, automerge-squash
