Repository dfinity/motoko, pull requests merged in 2024-12, with the labels that each got.

#4791 chore: use `macos-13` as `macos-12` is deprecated
  .github/workflows/release.yml
  .github/workflows/test.yml
  .mergify.yml
Labels: automerge-squash

#3827 chore: update `Timer.md` with caveats
  doc/md/base/Timer.md
Labels: automerge-squash

#4795 feat: add `prim deadline` for receiver-side best-effort messages
  Changelog.md
  nix/sources.json
  src/codegen/compile_classical.ml
  src/codegen/compile_enhanced.ml
  src/ir_def/arrange_ir.ml
  src/ir_def/check_ir.ml
  src/ir_def/ir.ml
  src/ir_interpreter/interpret_ir.ml
  src/lowering/desugar.ml
  src/mo_values/prim.ml
  src/prelude/prim.mo
  test/fail/ok/no-timer-canc.tc.ok
  test/fail/ok/no-timer-set.tc.ok
  test/fail/ok/suggest-long-ai.tc.ok
  test/fail/ok/suggest-short-ai.tc.ok
  test/run-drun/composite-query.mo
  test/run-drun/ok/composite-query.tc.ok
  test/run-drun/ok/query2.run-ir.ok
  test/run-drun/ok/query2.run-low.ok
  test/run-drun/ok/query2.run.ok
  test/run-drun/query2.mo
Labels: feature, automerge-squash

#4797 docs: update links for new docs validation
  doc/md/base/OrderedMap.md
  doc/md/base/OrderedSet.md
  doc/md/base/RBTree.md
  doc/md/writing-motoko/pattern-matching.md
Labels: automerge-squash

#4798 bugfix: bound subtyping depth to avoid reliance on unpredictable stack overflow
  src/lang_utils/error_codes.ml
  src/lang_utils/error_codes/M0200.md
  src/mo_frontend/typing.ml
  src/mo_types/type.ml
  src/mo_types/type.mli
  test/fail/issue-3057.mo
  test/fail/ok/issue-3057.tc.ok
  test/fail/ok/issue-3057.tc.ret.ok
  test/fail/ok/polyrec.tc.ok
  test/fail/ok/polyrec.tc.ret.ok
  test/fail/polyrec.mo
  test/run.sh
Labels: Bug

#4688 docs: add statement about import and actor sequence
  doc/md/writing-motoko/actors-async.md
Labels: automerge-squash

#4709 docs: add `StableTrie` as an option for stable memory storage based on `Region`s
  doc/md/stable-memory/stablememory.md
Labels: automerge-squash

#4805 chore: Releasing 0.13.5
  Changelog.md
Labels: automerge-squash

#4806 docs: Remove overview
  doc/md/canister-maintenance/compatibility.md
  doc/md/canister-maintenance/cycles.md
  doc/md/canister-maintenance/optimization.md
  doc/md/canister-maintenance/upgrades.md
  doc/md/getting-started/basic-concepts.md
  doc/md/getting-started/dev-env.md
  doc/md/getting-started/examples.md
  doc/md/getting-started/motoko-introduction.md
  doc/md/getting-started/quickstart.md
  doc/md/migration-guides/0.11.0-migration-guide.md
  doc/md/migration-guides/overview.md
  doc/md/motoko-tools/embed-motoko.md
  doc/md/motoko-tools/mo-dev.md
  doc/md/motoko-tools/motoko-formatter.md
  doc/md/motoko-tools/motoko-js.md
  doc/md/reference/compiler-ref.md
  doc/md/reference/generating-docs.md
  doc/md/reference/language-manual.md
  doc/md/reference/style.md
  doc/md/stable-memory/_category_.yml
  doc/md/stable-memory/stable-regions.md
  doc/md/stable-memory/stablememory.md
  doc/md/writing-motoko/actor-classes.md
  doc/md/writing-motoko/actors-async.md
  doc/md/writing-motoko/arguments.md
  doc/md/writing-motoko/async-data.md
  doc/md/writing-motoko/async-star.md
  doc/md/writing-motoko/caller-id.md
  doc/md/writing-motoko/candid-ui.md
  doc/md/writing-motoko/candid.md
  doc/md/writing-motoko/control-flow.md
  doc/md/writing-motoko/errors.md
  doc/md/writing-motoko/heartbeats.md
  doc/md/writing-motoko/incomplete-code.md
  doc/md/writing-motoko/integers.md
  doc/md/writing-motoko/intercanister-calls.md
  doc/md/writing-motoko/local-objects-classes.md
  doc/md/writing-motoko/message-inspection.md
  doc/md/writing-motoko/message-restrictions.md
  doc/md/writing-motoko/modules-and-imports.md
  doc/md/writing-motoko/mutable-state.md
  doc/md/writing-motoko/object-subtyping.md
  doc/md/writing-motoko/pattern-matching.md
  doc/md/writing-motoko/pipes.md
  doc/md/writing-motoko/query-functions.md
  doc/md/writing-motoko/randomness.md
  doc/md/writing-motoko/recursive-types.md
  doc/md/writing-motoko/sharing.md
  doc/md/writing-motoko/static-types.md
  doc/md/writing-motoko/structural-equality.md
  doc/md/writing-motoko/timers.md
  doc/md/writing-motoko/writing-intro.md
Labels: automerge-squash

#4814 chore: first cut of bot-modifiable files
  .github/repo_policies/BOT_APPROVED_FILES
Labels: automerge-squash

#4828 Fix small docu bug
  doc/md/canister-maintenance/compatibility.md
Labels: automerge-squash
