Repository dfinity/motoko, pull requests merged in 2025-06, with the labels that each got.

#5223 chore: update `author` for auto-approve rule in Mergify configuration
  .mergify.yml
Labels: automerge-squash

#5219 docs: Caller ID and Candid serialization pages
  doc/md/icp-features/3-caller-identification.md
  doc/md/icp-features/4-candid-serialization.md
Labels: automerge-squash

#5234 chore: update author condition for auto-approve rule in Mergify configuration
  .mergify.yml
Labels: automerge-squash

#5247 fix: typo
  doc/md/fundamentals/9-data-persistence.md
Labels: automerge-squash

#5254 chore: Releasing 0.14.12
  Changelog.md
Labels: automerge-squash, release

#5260 feat: speed up check_ir by caching sub, lub and check_typ tests
  Changelog.md
  src/ir_def/check_ir.ml
Labels: automerge-squash

#5256 feat: adds a primitive `Array_tabulateVar` function
  Changelog.md
  src/codegen/compile_classical.ml
  src/codegen/compile_enhanced.ml
  src/mo_values/prim.ml
  src/prelude/prim.mo
  test/fail/ok/no-timer-canc.tc.ok
  test/fail/ok/no-timer-set.tc.ok
  test/fail/ok/suggest-long-ai.tc.ok
  test/fail/ok/suggest-short-ai.tc.ok
  test/run/array-gen.mo
Labels: automerge-squash

#5270 chore: Releasing 0.14.13
  Changelog.md
Labels: release

#5288 fix(mo-doc): rewords heading for package index
  doc/md/base/index.md
  doc/md/core/index.md
  src/docs/html.ml
  src/docs/plain.ml
Labels: automerge-squash

#5299 chore: update docs
  doc/md/base/Text.md
Labels: automerge-squash
