Repository dfinity/motoko, pull requests merged in 2025-09, with the labels that each got.

#5445 chore: add `List.at()` in the docs
  doc/md/core/Array.md
  doc/md/core/Blob.md
  doc/md/core/Bool.md
  doc/md/core/Char.md
  doc/md/core/Cycles.md
  doc/md/core/Debug.md
  doc/md/core/Func.md
  doc/md/core/Int.md
  doc/md/core/Int16.md
  doc/md/core/Int32.md
  doc/md/core/Int64.md
  doc/md/core/Int8.md
  doc/md/core/List.md
  doc/md/core/Map.md
  doc/md/core/Nat.md
  doc/md/core/Nat16.md
  doc/md/core/Nat32.md
  doc/md/core/Nat64.md
  doc/md/core/Nat8.md
  doc/md/core/Principal.md
  doc/md/core/Queue.md
  doc/md/core/Random.md
  doc/md/core/Result.md
  doc/md/core/Set.md
  doc/md/core/Stack.md
  doc/md/core/Text.md
  doc/md/core/Types.md
  doc/md/core/VarArray.md
  doc/md/core/WeakReference.md
  doc/md/core/index.md
  doc/md/core/pure/List.md
  doc/md/core/pure/Queue.md
  flake.lock
Labels: automerge-squash

#5080 chore: prepare for a `rust-nightly` upgrade
  .github/actions/performance/action.yml
  nix/pkgs.nix
  nix/rts.nix
  rts/Makefile
  rts/motoko-rts-tests/Cargo.lock
  rts/motoko-rts-tests/src/main.rs
  rts/motoko-rts/Cargo.lock
  rts/motoko-rts/Cargo.toml
  rts/motoko-rts/src/float.rs
  rts/motoko-rts/src/lib.rs
  rts/motoko-rts/src/stream.rs
  rts/motoko-rts/wasm32-none-shared.json
  rts/motoko-rts/wasm64-none-shared.json
Labels: automerge-squash

#5493 refactor: remove code duplication in desugaring
  src/lowering/desugar.ml
Labels: automerge-squash

#5501 chore: add large runners for arm builds in CI
  .github/workflows/test.yml
Labels: automerge-squash

#5468 feat: Redundant type instantiation warning
  Changelog.md
  src/lang_utils/error_codes.ml
  src/mo_config/flags.ml
  src/mo_frontend/typing.ml
  test/fail/lambdas-core.mo
  test/fail/ok/lambdas-core.tc.ok
  test/run/ok/redundant-instantiations.tc.ok
  test/run/redundant-instantiations.mo
Labels: automerge-squash

#5502 feat: Warnings as Errors selectively
  Changelog.md
  doc/md/15-compiler-ref.md
  src/exes/moc.ml
  src/lang_utils/diag.ml
  src/lang_utils/error_codes.ml
  src/lang_utils/error_codes.mli
  src/mo_config/flags.ml
  test/fail/ok/warn-help.tc.ok
  test/fail/ok/warnings-as-errors.tc.ok
  test/fail/ok/warnings-as-errors.tc.ret.ok
  test/fail/warn-help.mo
  test/fail/warnings-as-errors.mo
Labels: automerge-squash

#5506 feat: Extra moc flags in vscode extension
  src/exes/moc.ml
  src/js/common.ml
  src/js/moc_js.ml
  src/lang_utils/diag.ml
  src/lang_utils/diag.mli
  src/lang_utils/mo_args.ml
  src/mo_config/args.ml
  src/mo_config/args.mli
Labels: automerge-squash, queued

#5528 chore: Releasing 0.16.3
  Changelog.md
Labels: automerge-squash, release, queued
