Repository dfinity/motoko, pull requests merged in 2025-03, with the labels that each got.

#4928 fix: Security best practice URL
  doc/md/writing-motoko/message-inspection.md
Labels: automerge-squash

#4929 feat: add primitive predicate `isReplicatedExecution`
  Changelog.md
  src/codegen/compile_classical.ml
  src/codegen/compile_enhanced.ml
  src/ir_def/construct.ml
  src/prelude/prim.mo
  test/fail/ok/no-timer-canc.tc.ok
  test/fail/ok/no-timer-set.tc.ok
  test/fail/ok/suggest-long-ai.tc.ok
  test/fail/ok/suggest-short-ai.tc.ok
  test/run-drun/ok/query.drun-run.ok
  test/run-drun/query.mo
Labels: feature, automerge-squash, canisters

#4932 chore: update `Changelog.md` with `base` changes
  Changelog.md
Labels: automerge-squash

#4947 Add `ocaml-lsp` dependency to `default.nix`
  default.nix
Labels: automerge-squash

#4948 chore: add `memory_metrics` to `canister_status`
  test/bench/candid-subtype-cost.mo
  test/bench/ok/candid-subtype-cost.drun-run.ok
Labels: automerge-squash

#4857 feat: implement `canisterSubnet` primitive
  Changelog.md
  src/codegen/compile_classical.ml
  src/codegen/compile_enhanced.ml
  src/mo_def/compUnit.ml
  src/mo_values/prim.ml
  src/prelude/prim.mo
  test/fail/ok/no-timer-canc.tc.ok
  test/fail/ok/no-timer-set.tc.ok
  test/fail/ok/suggest-long-ai.tc.ok
  test/fail/ok/suggest-short-ai.tc.ok
  test/run-drun/ok/upgrades.drun.ok
  test/run-drun/upgrades/upgrade0.mo
Labels: feature, automerge-squash, canisters

#4953 chore: update docs
  doc/md/base/Error.md
  doc/md/base/ExperimentalInternetComputer.md
Labels: automerge-squash

#4954 chore: Releasing 0.14.4
  Changelog.md
Labels: automerge-squash

#4957 chore: update `Changelog.md` with `base` additions
  Changelog.md
Labels: automerge-squash

#4958 chore: bump `nixpkgs`
  nix/sources.json
Labels: automerge-squash

#4962 chore: update `README.md` for ICP.ninja
  README.md
Labels: automerge-squash

#4961 chore: OCaml bump to 4.13
  default.nix
  nix/default.nix
  src/docs/.ocamlformat
  src/dune
  src/languageServer/.ocamlformat
  src/lib/lib.ml
  src/lib/lib.mli
  src/linking/linkModule.ml
  src/mo_frontend/suggest.ml
Labels: automerge-squash

#4963 feat: extract `let` bindings with manifest function type as honest-to-goodness `func`s
  doc/md/base/CertifiedData.md
  doc/md/base/Char.md
  doc/md/base/Error.md
  doc/md/base/ExperimentalCycles.md
  doc/md/base/ExperimentalInternetComputer.md
  doc/md/base/ExperimentalStableMemory.md
  doc/md/base/Float.md
  doc/md/base/Int16.md
  doc/md/base/Int32.md
  doc/md/base/Int64.md
  doc/md/base/Int8.md
  doc/md/base/Nat16.md
  doc/md/base/Nat32.md
  doc/md/base/Nat64.md
  doc/md/base/Nat8.md
  doc/md/base/None.md
  doc/md/base/OrderedMap.md
  doc/md/base/OrderedSet.md
  doc/md/base/Random.md
  doc/md/base/Region.md
  doc/md/base/Text.md
  doc/md/base/Time.md
  doc/md/base/Timer.md
  src/docs/extract.ml
Labels: automerge-squash, documentation

#4965 chore: use the stock `js_of_ocaml`
  nix/default.nix
  test/test-moc_interpreter.js
Labels: automerge-squash

#4972 chore: Releasing 0.14.5
  Changelog.md
Labels: automerge-squash

#4974 chore: bump OCaml to 4.14
  nix/default.nix
  src/docs/.ocamlformat
  src/docs/namespace.ml
  src/languageServer/.ocamlformat
  src/lib/lib.ml
  src/lib/lib.mli
Labels: automerge-squash

#4978 feat: detect lost fields in records (extensions)
  src/lang_utils/error_codes.ml
  src/mo_frontend/typing.ml
  test/fail/ok/check-record.tc.ok
  test/fail/ok/migration.tc.ok
  test/repl/ok/pretty-val.stderr.ok
  test/run-drun/ok/data-params.tc.ok
  test/run-drun/ok/issue2317.tc.ok
  test/run/object-extend.mo
  test/run/ok/object-extend.tc.ok
Labels: feature, automerge-squash

#4982 chore: bump `rustPlatform_moz_stable` (used for `drun`)
  nix/default.nix
Labels: automerge-squash, dependencies

#4952 chore: provide a tarballs for `Darwin-arm64` and `Linux-aarch64`
  .github/workflows/release.yml
  .github/workflows/test.yml
  default.nix
  release-files.nix
  test/bench/ok/region-mem.drun-run.ok
  test/bench/ok/region0-mem.drun-run.ok
  test/bench/ok/stable-mem.drun-run.ok
  test/run.sh
Labels: automerge-squash, github_actions

#4985 chore: don't `test/fail` in EOP mode, as no codegen is involved
  default.nix
Labels: automerge-squash
