Repository dfinity/motoko, pull requests merged in 2025-04, with the labels that each got.

#4988 chore: Releasing 0.14.6
  Changelog.md
Labels: automerge-squash

#4931 LSP: Implement a cache for typechecking (Serokell, Milestone-1)
  src/js/common.ml
  src/js/moc_js.ml
  src/pipeline/pipeline.ml
  src/pipeline/pipeline.mli
  test/test-moc.js
Labels: automerge-squash, ls, external-contributor

#4992 chore: supply `wasmtime` from `nixpkgs` 24.11
  nix/default.nix
  src/exes/candid_tests.ml
Labels: automerge-squash, tools, testing, dependencies

#4995 Fix RTS memory check
  rts/motoko-rts/src/gc/generational/sanity_checks.rs
  rts/motoko-rts/src/gc/incremental/phases/evacuation_increment.rs
Labels: Bug, automerge-squash

#4991 feat: improved `--stable-compatible` migration check
  Changelog.md
  doc/md/examples/Card-v1c.most
  doc/md/examples/grammar.txt
  src/lowering/desugar.ml
  src/mo_def/syntax.ml
  src/mo_frontend/parser.mly
  src/mo_frontend/printers.ml
  src/mo_frontend/stability.ml
  src/mo_frontend/typing.ml
  src/mo_types/type.ml
  src/mo_types/type.mli
  src/pipeline/pipeline.ml
  test/cmp/files/ver0.most
  test/cmp/files/ver1.most
  test/cmp/files/ver2.most
  test/cmp/files/ver3.most
  test/cmp/files/ver4.most
  test/cmp/files/ver5.most
  test/cmp/neg-ver1-0.cmp
  test/cmp/neg-ver2-1.cmp
  test/cmp/neg-ver3-2.cmp
  test/cmp/ok/neg-ver1-0.cmp.ok
  test/cmp/ok/neg-ver2-1.cmp.ok
  test/cmp/ok/neg-ver3-2.cmp.ok
  test/cmp/ok/ver0-1.cmp.ok
  test/cmp/ok/ver1-2.cmp.ok
  test/cmp/ok/ver2-3.cmp.ok
  test/cmp/ok/ver3-4.cmp.ok
  test/cmp/ok/ver4-5.cmp.ok
  test/cmp/ver0-1.cmp
  test/cmp/ver1-2.cmp
  test/cmp/ver2-3.cmp
  test/cmp/ver3-4.cmp
  test/cmp/ver4-5.cmp
Labels: feature, automerge-squash, canisters, enhancement

#5005 chore: Revert "deactivate `performance delta` for now"
  .github/workflows/test.yml
Labels: automerge-squash

#4943 feat: preserve named types in semantic types and when translating between Motoko and Candid
  Changelog.md
  src/idllib/arrange_idl.ml
  src/idllib/compile_js.ml
  src/idllib/parser.mly
  src/idllib/syntax.ml
  src/idllib/typing.ml
  src/ir_def/check_ir.ml
  src/ir_passes/async.ml
  src/ir_passes/erase_typ_field.ml
  src/ir_passes/erase_typ_field.mli
  src/mo_frontend/bi_match.ml
  src/mo_frontend/typing.ml
  src/mo_frontend/variance.ml
  src/mo_idl/idl_to_mo.ml
  src/mo_idl/mo_to_idl.ml
  src/mo_types/arrange_type.ml
  src/mo_types/expansive.ml
  src/mo_types/productive.ml
  src/mo_types/typ_hash.ml
  src/mo_types/type.ml
  src/mo_types/type.mli
  src/mo_values/operator.ml
  test/fail/ok/M0127.tc.ok
  test/fail/ok/abstract-msgs.tc.ok
  test/fail/ok/actor-class-non-shared.tc.ok
  test/fail/ok/bad-actor.tc.ok
  test/fail/ok/inference.tc.ok
  test/fail/ok/inspect_message_wrong.tc.ok
  test/fail/ok/invariant-inference.tc.ok
  test/fail/ok/issue-3318.tc.ok
  test/fail/ok/migration-bad.tc.ok
  test/fail/ok/no-timer-canc.tc.ok
  test/fail/ok/no-timer-set.tc.ok
  test/fail/ok/pat-subtyping-fail.tc.ok
  test/fail/ok/pipe-ill-typed.tc.ok
  test/fail/ok/pretty-inference.tc.ok
  test/fail/ok/pretty_scoped.tc.ok
  test/fail/ok/structural_equality.tc.ok
  test/fail/ok/suggest-long-ai.tc.ok
  test/fail/ok/suggest-short-ai.tc.ok
  test/fail/ok/variance.tc.ok
  test/lsp-int/Main.hs
  test/mo-idl/names.mo
  test/mo-idl/ok/class.did.ok
  test/mo-idl/ok/counter.did.ok
  test/mo-idl/ok/dup_fields.did.ok
  test/mo-idl/ok/fields.did.ok
  test/mo-idl/ok/inline_result.did.ok
  test/mo-idl/ok/issue-2529.did.ok
  test/mo-idl/ok/issue-827.did.ok
  test/mo-idl/ok/keyword.did.ok
  test/mo-idl/ok/names.did.ok
  test/mo-idl/ok/pa_cars.did.ok
  test/mo-idl/ok/prelude.did.ok
  test/mo-idl/ok/recursion.did.ok
  test/mo-idl/ok/result.did.ok
  test/repl/ok/named-types.stderr.ok
  test/repl/ok/named-types.stdout.ok
  test/repl/ok/pretty-val.stdout.ok
  test/repl/ok/type-lub-repl.stdout.ok
Labels: automerge-squash, typing, enhancement

#5006 throwaway: Update Changelog.md
  Changelog.md
Labels: DO-NOT-MERGE

#4979 feat: incremental partition growth for the incremental GC
  Changelog.md
  rts/motoko-rts/src/gc/incremental/partitioned_heap.rs
  test/run-drun/memory-base-usage-no-eop.mo
  test/run-drun/memory-base-usage.mo
  test/run-drun/ok/memory-base-usage-no-eop.drun-run.ok
  test/run-drun/ok/memory-base-usage.drun-run.ok
  test/run-drun/ok/upgrade-check-part-size-eop.drun.ok
  test/run-drun/ok/upgrade-check-part-size-incremental.drun.ok
  test/run-drun/upgrade-check-part-size-eop.drun
  test/run-drun/upgrade-check-part-size-eop/test.mo
  test/run-drun/upgrade-check-part-size-incremental.drun
  test/run-drun/upgrade-check-part-size-incremental/test.mo
  test/run.sh
Labels: automerge-squash, enhancement

#5007 chore: regenerate docs
  doc/md/base/ExperimentalCycles.md
Labels: automerge-squash, documentation

#5010 chore: Update Changelog.md
  Changelog.md
Labels: automerge-squash

#5011 chore: reproduce issue #4309
  test/mo-idl/import/issue-4309-types.mo
  test/mo-idl/issue-4309.mo
  test/mo-idl/ok/issue-4309.did.ok
Labels: automerge-squash, testing

#5014 chore: automatically push accepted `test/bench` numbers on `x86_64-linux`
  .github/workflows/test.yml
  .github/workflows/update-hash.yml
  default.nix
  test/bench/ok/region-mem.drun-run.ok
  test/bench/ok/region0-mem.drun-run.ok
  test/bench/ok/stable-mem.drun-run.ok
Labels: automerge-squash, tools, testing

#5023 chore: improves usage documentation for error code checking script
  test/check-error-codes.py
Labels: automerge-squash

#5027 chore: update `Changelog.md` with Serokell Milestone 2
  Changelog.md
Labels: automerge-squash

#5022 chore: fixes warnings in `src/`
  src/dune
  src/idllib/pipeline.ml
  src/idllib/resolve_import.ml
  src/idllib/resolve_import.mli
  src/languageServer/declaration_index.ml
Labels: automerge-squash

#5033 chore: support for splitting tests between `release` and `debug` builds
  .github/workflows/test.yml
  default.nix
Labels: automerge-squash

#5035 Officializing EOP after a successful beta testing phase
  Changelog.md
  design/OrthogonalPersistence.md
  design/PersistenceModes.md
  doc/md/canister-maintenance/orthogonal-persistence/classical.md
  doc/md/canister-maintenance/orthogonal-persistence/enhanced.md
  doc/md/canister-maintenance/orthogonal-persistence/modes.md
Labels: automerge-squash

#5043 feat: defines a tree-sitter based Motoko mode for Emacs
  emacs/motoko-ts-mode.el
Labels: automerge-squash

#5058 chore: Releasing 0.14.8
  Changelog.md
Labels: automerge-squash

#5068 chore: update `Building.md` (how to announce the release towards SDK)
  Building.md
Labels: automerge-squash

#5064 chore(docs): added release badge
  README.md
Labels: automerge-squash, external-contributor

#5071 chore: use `cachix watch-exec`
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: automerge-squash, testing

#5085 chore: add missing tools to get `make -C test` working again
  nix/shell.nix
Labels: automerge-squash

#5089 chore: allow `drun` to run as app subnet
  test/drun-wrapper.sh
  test/run-drun/check-app-subnet.drun
  test/run-drun/check-app-subnet/check-app-subnet.mo
  test/run-drun/check-system-subnet.drun
  test/run-drun/check-system-subnet/check-system-subnet.mo
  test/run-drun/ok/check-app-subnet.drun.ok
  test/run-drun/ok/check-system-subnet.drun.ok
  test/run.sh
Labels: automerge-squash

#5075 chore: deletes `mo-ide`
  design/DFX-Interface.md
  doc/attic/overview.md
  emacs/README.md
  emacs/init.el
  emacs/init_eglot.el
  flake.nix
  nix/check-formatting.nix
  nix/mo-packages.nix
  nix/pkgs.nix
  nix/tests.nix
  src/Makefile
  src/Structure.md
  src/exes/dune
  src/exes/mo_ide.ml
  src/languageServer/.ocamlformat
  src/languageServer/communication.ml
  src/languageServer/communication.mli
  src/languageServer/completion.ml
  src/languageServer/completion_test.ml
  src/languageServer/debug.ml
  src/languageServer/declaration_index.ml
  src/languageServer/declaration_index.mli
  src/languageServer/declaration_index_test.ml
  src/languageServer/definition.ml
  src/languageServer/dune
  src/languageServer/hover.ml
  src/languageServer/hover_tests.ml
  src/languageServer/imports.ml
  src/languageServer/languageServer.ml
  src/languageServer/languageServer.mli
  src/languageServer/pretty.ml
  src/languageServer/pretty.mli
  src/languageServer/source_file.ml
  src/languageServer/source_file_tests.ml
  src/languageServer/vfs.ml
  src/languageServer/vfs.mli
  src/languageServer/vfs_tests.ml
  src/lsp/atdAdapters.ml
  src/lsp/atdAdapters.mli
  src/lsp/diagnosticSeverity.ml
  src/lsp/diagnosticSeverity.mli
  src/lsp/dune
  src/lsp/lsp.atd
  src/lsp/messageType.ml
  src/lsp/messageType.mli
  test/lsp-int/Main.hs
  test/lsp-int/lsp-int.cabal
Labels: automerge-squash

#5106 feat: uses a new tree-sitter grammar for the Emacs mode
  emacs/motoko-ts-mode.el
Labels: automerge-squash

#5109 fix: removes more `mo-ide` leftovers
  .github/workflows/release.yml
  nix/release-files.nix
Labels: automerge-squash
