Repository dfinity/motoko, pull requests merged in 2025-01, with the labels that each got.

#4841 chore: test recovery procedure when `finally` traps
  test/drun-wrapper.sh
  test/run-drun/ok/try-finally-trap.drun.ok
  test/run-drun/try-finally-trap.drun
Labels: automerge-squash, testing

#4846 bugfix: check that timer servicing worked
  src/ir_def/construct.ml
  src/ir_def/construct.mli
  src/ir_passes/await.ml
  src/lowering/desugar.ml
  src/mo_frontend/typing.ml
  src/mo_frontend/typing.mli
  src/mo_types/type.ml
  src/mo_types/type.mli
  src/prelude/internals.mo
  test/fail/ok/illegal-await.tc.ok
Labels: Bug, automerge-squash

#4854 fix: Use lower case for Wasm persistence modes
  Changelog.md
  nix/drun.nix
  nix/sources.json
  src/mo_types/type.ml
  src/prelude/internals.mo
  test/bench/ok/region-mem.drun-run.ok
  test/bench/ok/region0-mem.drun-run.ok
  test/bench/ok/stable-mem.drun-run.ok
  test/run-drun/actor-class-mgmt-enhanced.mo
  test/run-drun/map-mixed-upgrades/map0.mo
  test/run-drun/map-mixed-upgrades/map1.mo
  test/run-drun/migration-paths/new-installer.mo
  test/run-drun/migration-paths/old-installer.mo
Labels: automerge-squash

#4856 chore: update `Changelog.md`
  Changelog.md
Labels: automerge-squash

#4858 chore: regenerate docs
  doc/md/base/Debug.md
  doc/md/base/ExperimentalInternetComputer.md
  doc/md/base/OrderedMap.md
  doc/md/base/OrderedSet.md
  doc/md/base/RBTree.md
  doc/md/base/Text.md
Labels: automerge-squash

#4868 feat: passing cycles to `call_raw`
  Changelog.md
  src/prelude/internals.mo
  test/run-drun/call-raw.mo
  test/run-drun/ok/call-raw.tc.ok
Labels: automerge-squash

#4872 chore: rebuild `base` docs
  doc/md/base/Debug.md
  doc/md/base/Error.md
  doc/md/base/ExperimentalInternetComputer.md
  doc/md/base/Timer.md
  doc/md/base/index.md
Labels: automerge-squash

#4871 docs: fix links
  doc/md/getting-started/quickstart.md
  doc/md/writing-motoko/arguments.md
Labels: automerge-squash
