Repository dfinity/motoko, pull requests merged in 2025-02, with the labels that each got.

#4878 docs: add syntax highlighting for `persistent` and `transient` keywords
  doc/docusaurus/src/theme/CodeBlock/hljs_run.js
  emacs/motoko-mode.el
Labels: automerge-squash

#4881 chore: Releasing 0.13.7
  Changelog.md
Labels: automerge-squash

#4883 chore: revise `Building.md` for the 0.14.x series
  Building.md
Labels: automerge-squash

#4886 chore: Releasing 0.14.0
  Changelog.md
Labels: automerge-squash

#4889 fix: relative link
  doc/md/canister-maintenance/upgrades.md
Labels: automerge-squash

#4891 doc: `make doc` without requiring nix magic
  doc/Makefile
  doc/docusaurus/src/pages/index.js
  doc/docusaurus/static/load_moc.ts
Labels: automerge-squash

#4896 chore: Releasing 0.14.1
  Changelog.md
Labels: automerge-squash

#4903 Update `README.md`
  README.md
Labels: automerge-squash

#4904 chore: update `README.md` link: `Building.md`
  README.md
Labels: automerge-squash

#4902 Update `CONTRIBUTING.md`
  .github/CONTRIBUTING.md
Labels: automerge-squash

#4905 bugfix: extend `mo-doc` to produce documentation for `actor` and `actor class` compilation units
  Changelog.md
  src/docs/extract.ml
Labels: automerge-squash, build_artifacts

#4897 fix: improve error highlighting range for `M0072`
  src/mo_frontend/typing.ml
  test/fail/ok/modexp1.tc.ok
  test/fail/ok/pretty.tc.ok
  test/fail/ok/suggest-long-ai.tc.ok
  test/fail/ok/suggest-long.tc.ok
  test/fail/ok/suggest-short-ai.tc.ok
  test/fail/ok/suggest-short.tc.ok
Labels: automerge-squash

#4908 fix: Doc links
  doc/md/canister-maintenance/cycles.md
  doc/md/canister-maintenance/upgrades.md
  doc/md/writing-motoko/candid-ui.md
  doc/md/writing-motoko/candid.md
Labels: automerge-squash

#4911 remove: Repeated sentence
  doc/md/writing-motoko/actors-async.md
Labels: automerge-squash

#4899 docs: (contributing)
  README.md
Labels: automerge-squash, external-contributor

#4919 docs: clarify inter-canister calls
  doc/md/writing-motoko/intercanister-calls.md
Labels: automerge-squash

#4921 chore: add missing primitive types to `motoko-mode.el`
  emacs/motoko-mode.el
Labels: automerge-squash

#4922 chore: Releasing 0.14.2
  Changelog.md
Labels: automerge-squash
