Repository dfinity/motoko, pull requests merged in 2025-08, with the labels that each got.

#5386 chore: fix warnings in moc_js
  src/codegen/compile_enhanced.ml
  src/exes/moc.ml
  src/mo_config/flags.ml
Labels: automerge-squash

#5398 chore: add `motoko-core` artifacts to GitHub releases
  nix/release-files-ubuntu-latest.nix
Labels: automerge-squash

#5401 feat: add program lifetime instruction counter
  src/codegen/compile_classical.ml
  src/codegen/compile_enhanced.ml
  src/mo_values/prim.ml
  src/prelude/prim.mo
  test/fail/ok/no-timer-canc.tc.ok
  test/fail/ok/no-timer-set.tc.ok
  test/fail/ok/suggest-long-ai.tc.ok
  test/fail/ok/suggest-short-ai.tc.ok
  test/run-drun/ok/test-lifetime-instr-counter.drun-run.ok
  test/run-drun/test-lifetime-instr-counter.mo
Labels: automerge-squash

#5410 doc: add note for creating `motoko-core` tag during release process
  Building.md
Labels: automerge-squash

#5412 bugfix: issue-5283 (repro and fix)
  Changelog.md
  src/ir_def/ir.ml
  src/ir_def/rename.ml
  test/run-drun/issue-5283.mo
  test/run-drun/ok/issue-5283.drun-run.ok
  test/run-drun/ok/issue-5283.tc.ok
Labels: Bug, automerge-squash

#5417 doc: migration guide tweaks
  doc/md/12-base-core-migration.md
Labels: automerge-squash

#5422 chore(license): removes modified boilerplate from license file
  LICENSE
Labels: automerge-squash

#5423 fix: Missing type note update (leaving `???` `Type.Pre`) in enhanced type inference path
  src/mo_frontend/typing.ml
  test/fail/lambdas-core.mo
Labels: automerge-squash

#5424 chore: Releasing 0.16.1
  Changelog.md
Labels: automerge-squash, release

#5434 fix: fix pocket-ic testing in the darwin x86 CI
  nix/pocket-ic.nix
  test-runner/Cargo.toml
Labels: automerge-squash

#5431 feat: parallel tests
  nix/tests.nix
  test/run-drun/Makefile
Labels: automerge-squash

#5432 Update `core` migration guide
  doc/md/12-base-core-migration.md
Labels: automerge-squash
