Repository dfinity/motoko, pull requests merged in 2025-05, with the labels that each got.

#5105 refactor: restructure CI to have less code repetition
  .github/actions/performance/action.yml
  .github/actions/test-blueprint/action.yml
  .github/workflows/test.yml
Labels: automerge-squash

#5120 chore: remove `macos + x86` from CI runs
  .github/workflows/nightly-macos-test.yml
  .github/workflows/test.yml
Labels: automerge-squash

#5125 chore: relax `dune` profile for local compilation
  src/Makefile
Labels: automerge-squash, testing

#5129 chore: rebuild docs
  doc/md/base/Int16.md
  doc/md/base/Int32.md
  doc/md/base/Int64.md
  doc/md/base/Nat16.md
  doc/md/base/Nat32.md
  doc/md/base/Nat64.md
Labels: automerge-squash, documentation

#5001 feat: implement system cost primitives
  Changelog.md
  src/codegen/compile_classical.ml
  src/codegen/compile_enhanced.ml
  src/prelude/prim.mo
  test/fail/ok/no-timer-canc.tc.ok
  test/fail/ok/no-timer-set.tc.ok
  test/fail/ok/suggest-long-ai.tc.ok
  test/fail/ok/suggest-short-ai.tc.ok
  test/run-drun-non-ci/test-cost/README.md
  test/run-drun-non-ci/test-cost/test-cost-create.mo
  test/run-drun-non-ci/test-cost/test-cost-ecdsa.mo
  test/run-drun-non-ci/test-cost/test-cost-http.mo
  test/run-drun-non-ci/test-cost/test-cost-schnorr.mo
  test/run-drun/cost.drun
  test/run-drun/cost/cost-simple-class.mo
  test/run-drun/cost/cost-simple-classical.mo
  test/run-drun/cost/cost-simple-enhanced.mo
  test/run-drun/ok/cost.drun.ok
Labels: feature, automerge-squash

#5133 chore: Releasing 0.14.10
  Changelog.md
Labels: automerge-squash

#5135 fix: Release 0.14.10
  Changelog.md
Labels: automerge-squash

#5076 LSP: syntax error examples, serialize ID locations, keep all origins in typechecker (Serokell, Milestone-3)
  doc/md/examples/grammar.txt
  nix/tests.nix
  src/Makefile
  src/js/common.ml
  src/js/moc_js.ml
  src/lang_utils/source.ml
  src/lang_utils/source.mli
  src/mo_config/flags.ml
  src/mo_def/arrange.ml
  src/mo_frontend/bi_match.ml
  src/mo_frontend/parser.mly
  src/mo_frontend/parsing.ml
  src/mo_frontend/parsing.mli
  src/mo_frontend/printers.ml
  src/mo_frontend/printers.mli
  src/mo_frontend/test_recovery.ml
  src/mo_frontend/typing.ml
  src/mo_types/arrange_type.ml
  src/mo_types/field_sources.ml
  src/mo_types/field_sources.mli
  src/mo_types/scope.ml
  src/mo_types/scope.mli
  src/mo_types/type.ml
  src/mo_types/type.mli
  src/pipeline/dune
  src/pipeline/pipeline.ml
  src/pipeline/pipeline.mli
  src/pipeline/test_field_srcs.ml
  test/fail/ok/stability.tc.ok
  test/fail/ok/syntax2.tc.ok
  test/fail/ok/syntax3.tc.ok
  test/fail/ok/syntax5.tc.ok
  test/test-moc.js
Labels: automerge-squash, external-contributor

#5142 chore: fixed broken link
  README.md
Labels: automerge-squash

#5145 chore: Releasing 0.14.11
  Changelog.md
Labels: automerge-squash

#5147 chore: instructions for other tools
  Building.md
Labels: automerge-squash

#5172 chore: add disk cleaning action
  .github/actions/test-blueprint/action.yml
Labels: automerge-squash

#5148 chore: upgrade `ic` to the latest `master`
  .github/actions/test-blueprint/action.yml
  flake.lock
  flake.nix
  nix/drun.nix
  nix/pkgs.nix
  test/run-drun/ok/incremental-actor-class-stabilization.drun-run.ok
  test/run-drun/ok/try-finally-trap-stop.drun-run.ok
  test/run.sh
Labels: automerge-squash, testing

#5132 refactor: Use alias for the `I` type in `IC.import_ic0` to have the same code between classical and enhanced
  src/codegen/compile_classical.ml
  src/codegen/compile_enhanced.ml
Labels: automerge-squash

#5173 draft: left-over suggestions
  doc/docusaurus/docusaurus.config.js
  doc/docusaurus/package-lock.json
  doc/md/fundamentals/2-types/12-advanced-types.md
  doc/md/fundamentals/2-types/14-subtyping.md
Labels: DO-NOT-MERGE
